# Generated by Django 5.2.15 on 2026-06-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='exit', upload_to='uploads/profiles/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
