# Generated by Django 5.2.15 on 2026-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_posts_options_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d'),
        ),
    ]
