# Generated by Django 5.2.15 on 2026-07-03 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_savedposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedposts',
            unique_together={('user', 'post')},
        ),
    ]
