# Generated by Django 5.2.15 on 2026-07-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_conversation_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='paticipants',
            new_name='participants',
        ),
    ]
